import Button from '../../ui/Button';
import SocialProofRow from '../SocialProofRow';
import { useTranslation } from 'react-i18next';
import TextInput from '../../ui/TextInput';
import TextArea from '../../ui/TextArea';
import Badge from '../../ui/Badge';
import Container from '../../layout/Container';

export default function ContactFormSection({ socialProofText }) {
  const { t } = useTranslation();

  return (
    <Container className="grid grid-cols-2 items-start gap-20 pb-20 pt-[calc(var(--nav-h)+40px)] max-[1199px]:gap-12 max-[809px]:grid-cols-1 max-[809px]:gap-9">
      <div className="rev"><Badge className="mb-6 inline-block rounded-full border border-[var(--border-mid)] bg-[var(--surface)] px-[14px] py-2 text-[13px] font-[var(--w500)] tracking-[var(--track)]">{t('contactForm.badge')}</Badge><h1 className="mb-5">{t('contactForm.titleLine1')}<br />{t('contactForm.titleLine2')}</h1><p className="max-w-[380px] text-[var(--muted)]">{t('contactForm.subtitle')}</p><SocialProofRow className="mt-6" initials={['S', 'J', 'M', 'A', '+']} text={socialProofText} /></div>
      <div className="rev flex flex-col gap-5">
        <div className="flex flex-col gap-[6px]"><label className="text-[13px] font-[var(--w500)] tracking-[var(--track)] text-[var(--color-primary)]">{t('contactForm.nameLabel')} <sup className="text-[var(--muted)]">*</sup></label><TextInput placeholder={t('contactForm.namePlaceholder')} /></div>
        <div className="flex flex-col gap-[6px]"><label className="text-[13px] font-[var(--w500)] tracking-[var(--track)] text-[var(--color-primary)]">{t('contactForm.emailLabel')} <sup className="text-[var(--muted)]">*</sup></label><TextInput type="email" placeholder={t('contactForm.emailPlaceholder')} /></div>
        <div className="flex flex-col gap-[6px]"><label className="text-[13px] font-[var(--w500)] tracking-[var(--track)] text-[var(--color-primary)]">{t('contactForm.servicesLabel')}</label><div className="flex flex-wrap gap-2"><label className="flex cursor-pointer items-center gap-[7px]"><input type="radio" name="service" className="h-[14px] w-[14px] cursor-pointer accent-[var(--color-primary)]" defaultChecked /> <span className="text-[13px] font-[var(--w500)] tracking-[var(--track)] text-[var(--color-primary)] cursor-pointer">{t('contactForm.services.contentCreation')}</span></label><label className="flex cursor-pointer items-center gap-[7px]"><input type="radio" name="service" className="h-[14px] w-[14px] cursor-pointer accent-[var(--color-primary)]" /> <span className="text-[13px] font-[var(--w500)] tracking-[var(--track)] text-[var(--color-primary)] cursor-pointer">{t('contactForm.services.socialManagement')}</span></label><label className="flex cursor-pointer items-center gap-[7px]"><input type="radio" name="service" className="h-[14px] w-[14px] cursor-pointer accent-[var(--color-primary)]" /> <span className="text-[13px] font-[var(--w500)] tracking-[var(--track)] text-[var(--color-primary)] cursor-pointer">{t('contactForm.services.paidMedia')}</span></label><label className="flex cursor-pointer items-center gap-[7px]"><input type="radio" name="service" className="h-[14px] w-[14px] cursor-pointer accent-[var(--color-primary)]" /> <span className="text-[13px] font-[var(--w500)] tracking-[var(--track)] text-[var(--color-primary)] cursor-pointer">{t('contactForm.services.all')}</span></label></div></div>
        <div className="flex flex-col gap-[6px]"><label className="text-[13px] font-[var(--w500)] tracking-[var(--track)] text-[var(--color-primary)]">{t('contactForm.budgetLabel')}</label><div className="flex flex-wrap gap-2"><label className="flex cursor-pointer items-center gap-[7px]"><input type="radio" name="budget" className="h-[14px] w-[14px] cursor-pointer accent-[var(--color-primary)]" defaultChecked /> <span className="text-[13px] font-[var(--w500)] tracking-[var(--track)] text-[var(--color-primary)] cursor-pointer">{t('contactForm.budgets.under2k')}</span></label><label className="flex cursor-pointer items-center gap-[7px]"><input type="radio" name="budget" className="h-[14px] w-[14px] cursor-pointer accent-[var(--color-primary)]" /> <span className="text-[13px] font-[var(--w500)] tracking-[var(--track)] text-[var(--color-primary)] cursor-pointer">{t('contactForm.budgets.between2k5k')}</span></label><label className="flex cursor-pointer items-center gap-[7px]"><input type="radio" name="budget" className="h-[14px] w-[14px] cursor-pointer accent-[var(--color-primary)]" /> <span className="text-[13px] font-[var(--w500)] tracking-[var(--track)] text-[var(--color-primary)] cursor-pointer">{t('contactForm.budgets.between5k10k')}</span></label><label className="flex cursor-pointer items-center gap-[7px]"><input type="radio" name="budget" className="h-[14px] w-[14px] cursor-pointer accent-[var(--color-primary)]" /> <span className="text-[13px] font-[var(--w500)] tracking-[var(--track)] text-[var(--color-primary)] cursor-pointer">{t('contactForm.budgets.over10k')}</span></label></div></div>
        <div className="flex flex-col gap-[6px]"><label className="text-[13px] font-[var(--w500)] tracking-[var(--track)] text-[var(--color-primary)]">{t('contactForm.businessLabel')} <sup className="text-[var(--muted)]">*</sup></label><TextArea placeholder={t('contactForm.businessPlaceholder')} /></div>
        <Button fullWidth size="lg" type="button">{t('contactForm.submit')}</Button>
      </div>
    </Container>
  );
}
